server:
  port: 0
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: module_b
    password: module_b


consumer:
  exchange: ""
  type: direct
  routeKey: requests


OMDB:
  baseUrl: http://www.omdbapi.com/
