spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: module_a
    password: module_a
producer:
  exchange: ""
  type: direct
  routeKey: requests
consumer:
  exchange: ""
  type: direct
  routeKey: responses

OMDB:
  baseUrl: http://www.omdbapi.com/
